### ISSUE TITLE
查成分报错相关

### ISSUE THREAD

**Issue by benx1n** [benx1n/hoshinobot-plugin-ddcheck#1]
noneplugin/nonebot-plugin-ddcheck#6

**Comment by benx1n** [comment]
已推送修复，请拉取最新代码后重新安装依赖 
![image](https://user-images.githubusercontent.com/48101337/167005296-d720fe1e-3ddf-4312-a916-ce21d6610912.png)

**Comment by SanaChitose** [comment]
> 已推送修复，请拉取最新代码后重新安装依赖 ![image](https://user-images.githubusercontent.com/48101337/167005296-d720fe1e-3ddf-4312-a916-ce21d6610912.png)
感谢本心佬回复！已安装最新版依赖后重启，
PS C:\Users\Administrator\Desktop\hoshinobot-plugin-ddcheck> pip install -r requirements.txt

Requirement already satisfied: aiofiles~=0.8.0 in c:\users\administrator\appdata\local\programs\python\python38-32\lib\s
ite-packages (from -r requirements.txt (line 1)) (0.8.0)

Requirement already satisfied: httpx~=0.22.0 in c:\users\administrator\appdata\local\programs\python\python38-32\lib\sit
e-packages (from -r requirements.txt (line 2)) (0.22.0)

Requirement already satisfied: Jinja2~=3.0.3 in c:\users\administrator\appdata\local\programs\python\python38-32\lib\sit
e-packages (from -r requirements.txt (line 3)) (3.0.3)

Requirement already satisfied: loguru~=0.6.0 in c:\users\administrator\appdata\local\programs\python\python38-32\lib\sit
e-packages (from -r requirements.txt (line 4)) (0.6.0)

Requirement already satisfied: Markdown~=3.3.6 in c:\users\administrator\appdata\local\programs\python\python38-32\lib\s
ite-packages (from -r requirements.txt (line 5)) (3.3.6)

Requirement already satisfied: nonebot~=1.9.1 in c:\users\administrator\appdata\local\programs\python\python38-32\lib\si
te-packages (from -r requirements.txt (line 6)) (1.9.1)

Requirement already satisfied: Pillow~=9.1.0 in c:\users\administrator\appdata\local\programs\python\python38-32\lib\sit
e-packages (from -r requirements.txt (line 7)) (9.1.0)

Requirement already satisfied: playwright~=1.20.1 in c:\users\administrator\appdata\local\programs\python\python38-32\li
b\site-packages (from -r requirements.txt (line 8)) (1.20.1)

Requirement already satisfied: sniffio in c:\users\administrator\appdata\local\programs\python\python38-32\lib\site-pack
ages (from httpx~=0.22.0->-r requirements.txt (line 2)) (1.2.0)

Requirement already satisfied: rfc3986[idna2008]<2,>=1.3 in c:\users\administrator\appdata\local\programs\python\python3
8-32\lib\site-packages (from httpx~=0.22.0->-r requirements.txt (line 2)) (1.5.0)

Requirement already satisfied: charset-normalizer in c:\users\administrator\appdata\local\programs\python\python38-32\li
b\site-packages (from httpx~=0.22.0->-r requirements.txt (line 2)) (2.0.12)

Requirement already satisfied: httpcore<0.15.0,>=0.14.5 in c:\users\administrator\appdata\local\programs\python\python38
-32\lib\site-packages (from httpx~=0.22.0->-r requirements.txt (line 2)) (0.14.7)

Requirement already satisfied: certifi in c:\users\administrator\appdata\local\programs\python\python38-32\lib\site-pack
ages (from httpx~=0.22.0->-r requirements.txt (line 2)) (2021.10.8)

Requirement already satisfied: MarkupSafe>=2.0 in c:\users\administrator\appdata\local\programs\python\python38-32\lib\s
ite-packages (from Jinja2~=3.0.3->-r requirements.txt (line 3)) (2.1.1)

Requirement already satisfied: colorama>=0.3.4 in c:\users\administrator\appdata\local\programs\python\python38-32\lib\s
ite-packages (from loguru~=0.6.0->-r requirements.txt (line 4)) (0.4.4)

Requirement already satisfied: win32-setctime>=1.0.0 in c:\users\administrator\appdata\local\programs\python\python38-32
\lib\site-packages (from loguru~=0.6.0->-r requirements.txt (line 4)) (1.1.0)

Requirement already satisfied: importlib-metadata>=4.4 in c:\users\administrator\appdata\local\programs\python\python38-
32\lib\site-packages (from Markdown~=3.3.6->-r requirements.txt (line 5)) (4.11.3)

Requirement already satisfied: aiocqhttp>=1.3 in c:\users\administrator\appdata\local\programs\python\python38-32\lib\si
te-packages (from nonebot~=1.9.1->-r requirements.txt (line 6)) (1.4.2)

Requirement already satisfied: aiocache<1.0,>=0.10 in c:\users\administrator\appdata\local\programs\python\python38-32\l
ib\site-packages (from nonebot~=1.9.1->-r requirements.txt (line 6)) (0.11.1)

Requirement already satisfied: websockets==10.1 in c:\users\administrator\appdata\local\programs\python\python38-32\lib\
site-packages (from playwright~=1.20.1->-r requirements.txt (line 8)) (10.1)

Requirement already satisfied: typing-extensions in c:\users\administrator\appdata\local\programs\python\python38-32\lib
\site-packages (from playwright~=1.20.1->-r requirements.txt (line 8)) (4.2.0)

Requirement already satisfied: greenlet==1.1.2 in c:\users\administrator\appdata\local\programs\python\python38-32\lib\s
ite-packages (from playwright~=1.20.1->-r requirements.txt (line 8)) (1.1.2)

Requirement already satisfied: pyee==8.1.0 in c:\users\administrator\appdata\local\programs\python\python38-32\lib\site-
packages (from playwright~=1.20.1->-r requirements.txt (line 8)) (8.1.0)

Requirement already satisfied: Quart<0.15,>=0.14 in c:\users\administrator\appdata\local\programs\python\python38-32\lib
\site-packages (from aiocqhttp>=1.3->nonebot~=1.9.1->-r requirements.txt (line 6)) (0.14.1)

Requirement already satisfied: anyio==3.* in c:\users\administrator\appdata\local\programs\python\python38-32\lib\site-p
ackages (from httpcore<0.15.0,>=0.14.5->httpx~=0.22.0->-r requirements.txt (line 2)) (3.5.0)

Requirement already satisfied: h11<0.13,>=0.11 in c:\users\administrator\appdata\local\programs\python\python38-32\lib\s
ite-packages (from httpcore<0.15.0,>=0.14.5->httpx~=0.22.0->-r requirements.txt (line 2)) (0.12.0)

Requirement already satisfied: idna>=2.8 in c:\users\administrator\appdata\local\programs\python\python38-32\lib\site-pa
ckages (from anyio==3.*->httpcore<0.15.0,>=0.14.5->httpx~=0.22.0->-r requirements.txt (line 2)) (3.3)

Requirement already satisfied: zipp>=0.5 in c:\users\administrator\appdata\local\programs\python\python38-32\lib\site-pa
ckages (from importlib-metadata>=4.4->Markdown~=3.3.6->-r requirements.txt (line 5)) (3.8.0)

Requirement already satisfied: hypercorn>=0.7.0 in c:\users\administrator\appdata\local\programs\python\python38-32\lib\
site-packages (from Quart<0.15,>=0.14->aiocqhttp>=1.3->nonebot~=1.9.1->-r requirements.txt (line 6)) (0.13.2)

Requirement already satisfied: toml in c:\users\administrator\appdata\local\programs\python\python38-32\lib\site-package
s (from Quart<0.15,>=0.14->aiocqhttp>=1.3->nonebot~=1.9.1->-r requirements.txt (line 6)) (0.10.2)

Requirement already satisfied: werkzeug>=1.0.0 in c:\users\administrator\appdata\local\programs\python\python38-32\lib\s
ite-packages (from Quart<0.15,>=0.14->aiocqhttp>=1.3->nonebot~=1.9.1->-r requirements.txt (line 6)) (2.0.3)

Requirement already satisfied: click in c:\users\administrator\appdata\local\programs\python\python38-32\lib\site-packag
es (from Quart<0.15,>=0.14->aiocqhttp>=1.3->nonebot~=1.9.1->-r requirements.txt (line 6)) (8.1.3)

Requirement already satisfied: blinker in c:\users\administrator\appdata\local\programs\python\python38-32\lib\site-pack
ages (from Quart<0.15,>=0.14->aiocqhttp>=1.3->nonebot~=1.9.1->-r requirements.txt (line 6)) (1.4)

Requirement already satisfied: itsdangerous in c:\users\administrator\appdata\local\programs\python\python38-32\lib\site
-packages (from Quart<0.15,>=0.14->aiocqhttp>=1.3->nonebot~=1.9.1->-r requirements.txt (line 6)) (2.1.2)

Requirement already satisfied: wsproto>=0.14.0 in c:\users\administrator\appdata\local\programs\python\python38-32\lib\s
ite-packages (from hypercorn>=0.7.0->Quart<0.15,>=0.14->aiocqhttp>=1.3->nonebot~=1.9.1->-r requirements.txt (line 6)) (1
.1.0)

Requirement already satisfied: h2>=3.1.0 in c:\users\administrator\appdata\local\programs\python\python38-32\lib\site-pa
ckages (from hypercorn>=0.7.0->Quart<0.15,>=0.14->aiocqhttp>=1.3->nonebot~=1.9.1->-r requirements.txt (line 6)) (4.1.0)

Requirement already satisfied: priority in c:\users\administrator\appdata\local\programs\python\python38-32\lib\site-pac
kages (from hypercorn>=0.7.0->Quart<0.15,>=0.14->aiocqhttp>=1.3->nonebot~=1.9.1->-r requirements.txt (line 6)) (2.0.0)

Requirement already satisfied: hyperframe<7,>=6.0 in c:\users\administrator\appdata\local\programs\python\python38-32\li
b\site-packages (from h2>=3.1.0->hypercorn>=0.7.0->Quart<0.15,>=0.14->aiocqhttp>=1.3->nonebot~=1.9.1->-r requirements.txt (line 6)) (6.0.1)

Requirement already satisfied: hpack<5,>=4.0 in c:\users\administrator\appdata\local\programs\python\python38-32\lib\sit
e-packages (from h2>=3.1.0->hypercorn>=0.7.0->Quart<0.15,>=0.14->aiocqhttp>=1.3->nonebot~=1.9.1->-r requirements.txt (line 6)) (4.0.0)

仍然报错：
![图片](https://user-images.githubusercontent.com/102790983/167054547-e1db3c73-c565-4bde-beae-5a7277884f5e.png)

报错具体代码为：
[2022-05-06 09:56:40,804 nonebot] INFO: Self: 3411935041, Message -1131559107 from 93*******14@[群:10*****450]: '查成分hanser'

[2022-05-06 09:56:40,804 ddcheck] INFO: Message -1131559107 triggered ddcheck.

Task exception was never retrieved

future: <Task finished name='Task-69' coro=<Connection.run() done, defined at C:\Users\Administrator\AppData\Local\Progr
ams\Python\Python38-32\lib\site-packages\playwright\_impl\_connection.py:175> exception=NotImplementedError()>

Traceback (most recent call last):

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\playwright\_impl\_connection.
py", line 182, in run

    await self._transport.connect()

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\playwright\_impl\_transport.p
y", line 140, in connect

    raise exc

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\playwright\_impl\_transport.p
y", line 128, in connect

    self._proc = await asyncio.create_subprocess_exec(

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\asyncio\subprocess.py", line 236, in create
_subprocess_exec

    transport, protocol = await loop.subprocess_exec(

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 1630, in subp
rocess_exec

    transport = await self._make_subprocess_transport(

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 491, in _make
_subprocess_transport

    raise NotImplementedError

NotImplementedError

[2022-05-06 09:56:41,614 nonebot] WARNING: Traceback (most recent call last):

  File "C:\bot\HoshinoBot\hoshino\modules\hoshinobot-plugin-ddcheck\__init__.py", line 43, in ddcheck

    res = await get_reply(text)

  File "C:\bot\HoshinoBot\hoshino\modules\hoshinobot-plugin-ddcheck\data_source.py", line 184, in get_reply

    return await html_to_pic(content, wait=0, viewport={"width": 100, "height": 100})

  File "C:\bot\HoshinoBot\hoshino\modules\hoshinobot-plugin-ddcheck\htmlrender.py", line 159, in html_to_pic

    async with get_new_page(**kwargs) as page:

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\contextlib.py", line 171, in __aenter__

    return await self.gen.__anext__()

  File "C:\bot\HoshinoBot\hoshino\modules\hoshinobot-plugin-ddcheck\browser.py", line 45, in get_new_page

    browser = await get_browser()

  File "C:\bot\HoshinoBot\hoshino\modules\hoshinobot-plugin-ddcheck\browser.py", line 40, in get_browser

    return _browser or await init(**kwargs)

  File "C:\bot\HoshinoBot\hoshino\modules\hoshinobot-plugin-ddcheck\browser.py", line 26, in init

    _playwright = await async_playwright().start()

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\playwright\async_api\_context
_manager.py", line 51, in start

    return await self.__aenter__()

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\playwright\async_api\_context
_manager.py", line 46, in __aenter__

    playwright = AsyncPlaywright(next(iter(done)).result())

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\playwright\_impl\_connection.
py", line 182, in run

    await self._transport.connect()

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\playwright\_impl\_transport.p
y", line 140, in connect

    raise exc

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\playwright\_impl\_transport.p
y", line 128, in connect

    self._proc = await asyncio.create_subprocess_exec(

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\asyncio\subprocess.py", line 236, in create
_subprocess_exec

    transport, protocol = await loop.subprocess_exec(

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 1630, in subp
rocess_exec

    transport = await self._make_subprocess_transport(

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 491, in _make
_subprocess_transport

    raise NotImplementedError

NotImplementedError
禁用色图插件后可以正常使用，冲突的涩图插件为：https://github.com/pcrbot/setu_renew

**Comment by benx1n** [comment]
尝试将ddcheck在bot.py中配置在setu_renew的上方，两个都启用再试试看

**Comment by SanaChitose** [comment]
> 尝试将ddcheck在bot.py中配置在setu_renew的上方，两个都启用再试试看

![图片](https://user-images.githubusercontent.com/102790983/167055988-a881011f-05d8-4737-98f6-75caa1de3d77.png)
尝试过各种排列组合方式，还是没有用
![图片](https://user-images.githubusercontent.com/102790983/167056305-588558bd-946f-4ab3-aff2-149d4ac4bf49.png)

**Comment by benx1n** [comment]
看起来是playwright的协程问题，还有装什么其他插件吗

**Comment by benx1n** [comment]
kexue-z/nonebot-plugin-htmlrender#15

**Comment by SanaChitose** [comment]
> 看起来是playwright的协程问题，还有装什么其他插件吗

![图片](https://user-images.githubusercontent.com/102790983/167060804-c711ce2d-5a07-4681-a5e8-071d76662754.png)
插件比较多，其中涉及网页操作（内容转换成图片输出）的可能为：hoshinobot-plugin-ddcheck，steam_crawler_botV2，setu_renew，yiqing_HoshinoBot，pulipuli，yaowoyizhi，image-generate，hoshinobot-plugin-petpet，都可以在https://github.com/pcrbot/HoshinoBot-plugins-index目录中找到

**Comment by MeetWq** [comment]
我看了一下setu_renew插件，它改了默认事件循环策略，就是这里导致的问题

https://github.com/pcrbot/setu_renew/blob/7d9339d9ec9593aeb4b0e505d96845be468eb38e/acggov.py#L18

**Comment by SanaChitose** [comment]
> 我看了一下setu_renew插件，它改了默认事件循环策略，就是这里导致的问题
> 
> https://github.com/pcrbot/setu_renew/blob/7d9339d9ec9593aeb4b0e505d96845be468eb38e/acggov.py#L18

大佬牛哇！这种情况为了避免以后可能出现的问题，我是不是换个涩图插件比较好？

**Comment by benx1n** [comment]
> 我看了一下setu_renew插件，它改了默认事件循环策略，就是这里导致的问题
> 
> https://github.com/pcrbot/setu_renew/blob/7d9339d9ec9593aeb4b0e505d96845be468eb38e/acggov.py#L18

确实，这里强制指定了事件循环，虽然不太清楚为什么要这么做，但在windows上playwright无法与SelectorEventLoop兼容，py3.8+中已经将事件选择器默认置为ProactorEventLoop，您可以尝试注释这段后看看setu_renew会出现什么异常，实在不行的话我暂时也没想到啥好的兼容办法 @SanaChitose

**Comment by MeetWq** [comment]
setu_renew这样写应该是因为aiohttp在windows上用代理会出问题
https://github.com/aio-libs/aiohttp/issues/4536
建议改用httpx ()

**Comment by SanaChitose** [comment]
> > 我看了一下setu_renew插件，它改了默认事件循环策略，就是这里导致的问题
> > https://github.com/pcrbot/setu_renew/blob/7d9339d9ec9593aeb4b0e505d96845be468eb38e/acggov.py#L18
> 
> 确实，这里强制指定了事件循环，虽然不太清楚为什么要这么做，但在windows上playwright无法与SelectorEventLoop兼容，py3.8+中已经将事件选择器默认置为ProactorEventLoop，您可以尝试注释这段后看看setu_renew会出现什么异常，实在不行的话我暂时也没想到啥好的兼容办法 @SanaChitose

注释掉这段代码以后可以成功运行了，感谢本心佬！
![图片](https://user-images.githubusercontent.com/102790983/167063443-08286538-88fc-4ae7-b9c2-bcdfa5b270b3.png)
按setu_renew作者所说acggov源已经废弃，对于我这种不用acggov功能的用户大概可以放心大胆注释掉（

**Comment by benx1n** [comment]
> setu_renew这样写应该是因为aiohttp在windows上用代理会出问题
> [aio-libs/aiohttp#4536](https://github.com/aio-libs/aiohttp/issues/4536)
> 建议改用httpx ()

Orz稍后我向那边开个pr，虽然看作者的意思是已经弃用了acggov）
