### ISSUE TITLE
安装了loguru模块控制台还是报错没有loguru

### ISSUE THREAD

**Issue by MarshyCoco** [benx1n/hoshinobot-plugin-ddcheck#10]
![QQ截图20221208022829](https://user-images.githubusercontent.com/54161947/206266048-c7ef359c-312e-4eae-9899-74b2cdc08a5f.png)
![QQ截图20221208021746](https://user-images.githubusercontent.com/54161947/206266057-3c8879f7-65f0-4426-a73e-145f7147f3f3.png)

**Comment by benx1n** [comment]
之前一直没看issue，现在还能复现这个问题吗）
