### ISSUE TITLE
查询制图成功，但数据不对

### ISSUE THREAD

**Issue by ElizaKzi** [benx1n/hoshinobot-plugin-ddcheck#4]
![OY7_37I}B3(DWBM2QWSKARM](https://user-images.githubusercontent.com/63360445/177149429-3cd3b7be-1ee2-41d3-bedf-d2e31be96fdf.PNG)
这是我朋友的，显示0%，但是实际上d了很多v
![_MX89}WK$QZSY280QOLH)D3](https://user-images.githubusercontent.com/63360445/177149522-f1f2135f-05ce-4e16-a00c-b3d7ad1ff5ec.PNG)
![0K1S(L7 A7XDYFHLUA5C$T](https://user-images.githubusercontent.com/63360445/177149567-7c33ceb2-b040-4123-9f70-1e3eb12868c1.PNG)
![E55CM1WD}L)FT@1)WHZUP83](https://user-images.githubusercontent.com/63360445/177149610-c92d3ea1-3dd2-4dcc-94be-4616c1913f25.PNG)
其他人的并没有问题

**Comment by deepdarkssj** [comment]
猜测是由于锁了关注列表导致没查到，最近b站更新了接口导致在隐私设置里设定不公开关注列表时这个接口拿不到列表数据了

**Comment by benx1n** [comment]
是B站把这个接口的漏洞修复了，以前隐藏了关注列表的也可以通过这个来查询
